name: Release

on:
  release:
    types:
      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0

    - name: Execute command in server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: source /home/crrmacarse/www/api/bin/deploy.sh $GITHUB_SHA
